server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: app-service
          uri: lb://APP-SERVICE
          predicates:
            - Path=/api/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
