server:
  port: 3000

spring:
  cloud:
    gateway:
      routes:
        - id: app-service
          uri: lb://APP-SERVICE
          predicates:
            - Path=/api/**
            - Path=/login



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
